"use client";

import Link from "next/link";
import { useEffect, useState } from "react";
import { usePreferences } from "@/components/preferences/preferences-provider";
import type { AnalyticsData } from "@/lib/analytics/live-dashboard";

export function AnalyticsDashboard({ initialData }: { initialData: AnalyticsData }) {
  const [data, setData] = useState(initialData); const [days, setDays] = useState(initialData.days); const [connected, setConnected] = useState(true);
  useEffect(() => {
    let cancelled = false;
    const refresh = async () => { if (document.visibilityState !== "visible") return; try { const response = await fetch(`/api/admin/analytics?days=${days}`, { cache: "no-store" }); if (!response.ok) throw new Error(); const next = await response.json() as AnalyticsData; if (!cancelled) { setData(next); setConnected(true); } } catch { if (!cancelled) setConnected(false); } };
    void refresh(); const timer = setInterval(refresh, 15_000); return () => { cancelled = true; clearInterval(timer); };
  }, [days]);
  return <div>
    <div className="flex flex-col gap-5 lg:flex-row lg:items-end lg:justify-between"><div><p className="text-xs uppercase tracking-[0.22em] text-gold">Business intelligence</p><h2 className="mt-2 font-serif text-5xl">Performance analytics</h2><p className="mt-3 max-w-3xl text-sm leading-6 text-muted">Live sales, service, AI, and knowledge performance from verified operational records.</p></div><div className="flex flex-wrap items-center gap-2"><LiveBadge connected={connected} generatedAt={data.generatedAt} />{[7, 30, 90].map((value) => <button key={value} type="button" onClick={() => setDays(value)} className={days === value ? "btn-gold" : "btn-ghost"}>{value} days</button>)}</div></div>
    <div className="mt-8 grid gap-4 sm:grid-cols-2 xl:grid-cols-4">{data.metrics.map((metric) => <MetricCard key={metric.label} metric={metric} currency={data.currency} />)}</div>
    <div className="mt-6 grid gap-6 xl:grid-cols-[1.4fr_0.6fr]">
      <section className="admin-card rounded-3xl p-6 sm:p-8"><div className="flex items-start justify-between"><div><p className="text-xs uppercase tracking-[0.2em] text-gold">Trend</p><h3 className="mt-2 font-serif text-3xl">Conversations and bookings</h3></div><span className="text-xs text-muted">Daily</span></div><ActivityChart series={data.series} /><div className="mt-5 flex gap-5 text-xs text-muted"><span className="flex items-center gap-2"><i className="h-2 w-2 rounded-full bg-gold" /> Conversations</span><span className="flex items-center gap-2"><i className="h-2 w-2 rounded-full bg-ok" /> Bookings</span></div></section>
      <section className="admin-card rounded-3xl p-6 sm:p-8"><p className="text-xs uppercase tracking-[0.2em] text-gold">Sales funnel</p><h3 className="mt-2 font-serif text-3xl">From chat to booking</h3><div className="mt-7 space-y-5"><FunnelRow label="Conversations" value={data.funnel.conversations} base={data.funnel.conversations} /><FunnelRow label="Qualified chats" value={data.funnel.quotedConversations} base={data.funnel.conversations} /><FunnelRow label="Quotes created" value={data.funnel.quotes} base={data.funnel.conversations} /><FunnelRow label="Bookings confirmed" value={data.funnel.bookings} base={data.funnel.conversations} /></div></section>
    </div>
    <div className="mt-6 grid gap-6 lg:grid-cols-3">
      <section className="admin-card rounded-3xl p-6"><p className="text-xs uppercase tracking-[0.2em] text-gold">Operations</p><div className="mt-5 grid grid-cols-2 gap-3"><SmallMetric label="Open escalations" value={data.operations.openEscalations} /><SmallMetric label="Resolution rate" value={`${data.operations.resolutionRate.toFixed(1)}%`} /><SmallMetric label="AI success" value={`${data.operations.aiSuccessRate.toFixed(1)}%`} /><SmallMetric label="Knowledge misses" value={data.operations.knowledgeMisses} /></div></section>
      <section className="admin-card rounded-3xl p-6"><div className="flex items-center justify-between"><p className="text-xs uppercase tracking-[0.2em] text-gold">Top vehicles</p><Link href="/admin/fleet" className="text-xs text-gold">Fleet →</Link></div><RankedList rows={data.topVehicles.map((item) => ({ label: item.name, value: `${item.bookings} bookings · ${formatCurrency(item.revenue, data.currency)}` }))} empty="No vehicle activity yet." /></section>
      <section className="admin-card rounded-3xl p-6"><div className="flex items-center justify-between"><p className="text-xs uppercase tracking-[0.2em] text-gold">Escalation causes</p><Link href="/admin/escalations" className="text-xs text-gold">Review →</Link></div><RankedList rows={data.escalationReasons.map((item) => ({ label: humanize(item.reason), value: String(item.count) }))} empty="No escalations in this period." /></section>
    </div>
    <section className="admin-card mt-6 rounded-3xl p-6 sm:p-8"><div><p className="text-xs uppercase tracking-[0.2em] text-gold">Latency evidence</p><h3 className="mt-2 font-serif text-3xl">Production SLO percentiles</h3><p className="mt-2 text-sm text-muted">Calculated from real webhook, context, tool, and complete-processing measurements in the selected period. A target only passes when samples exist and p95 is within budget.</p></div><div className="mt-6 grid gap-3 md:grid-cols-2 xl:grid-cols-4">{data.latencySlo.map((row) => <div key={row.key} className="rounded-2xl bg-panel-2/60 p-4"><div className="flex justify-between gap-2"><p className="text-xs text-muted">{row.label}</p><span className={`text-[10px] uppercase ${row.passing ? "text-ok" : "text-danger"}`}>{row.samples ? row.passing ? "Passing" : "Over target" : "Awaiting data"}</span></div><p className="mt-4 font-serif text-2xl text-gold-2" data-no-translate>{row.p95 == null ? "—" : `${row.p95}ms`}</p><p className="mt-1 text-xs text-muted" data-no-translate>p95 · target {row.targetMs}ms</p><p className="mt-3 text-[10px] text-muted" data-no-translate>{row.samples} samples · p50 {row.p50 == null ? "—" : `${row.p50}ms`}</p></div>)}</div></section>
  </div>;
}

function MetricCard({ metric, currency }: { metric: AnalyticsData["metrics"][number]; currency: string }) { return <article className="admin-card rounded-3xl p-5"><div className="flex items-start justify-between gap-3"><p className="text-xs uppercase tracking-[0.17em] text-muted">{metric.label}</p>{metric.change == null ? <span className="text-[10px] text-muted">New</span> : <span className={`rounded-full px-2 py-1 text-[10px] ${metric.positive ? "bg-ok/10 text-ok" : "bg-danger/10 text-danger"}`} data-no-translate>{metric.change >= 0 ? "+" : ""}{metric.change.toFixed(1)}%</span>}</div><p className="mt-6 font-serif text-4xl text-gold-2" data-no-translate>{formatMetric(metric.value, metric.format, currency)}</p><p className="mt-2 text-xs text-muted">Compared with previous period</p></article>; }
function ActivityChart({ series }: { series: AnalyticsData["series"] }) { const max = Math.max(1, ...series.map((item) => Math.max(item.conversations, item.bookings))); const visible = series.length > 30 ? series.filter((_, index) => index % 3 === 0 || index === series.length - 1) : series; return <div className="mt-8 flex h-56 items-end gap-1.5 border-b border-line pb-1" data-no-translate>{visible.map((item) => <div key={item.date} className="group relative flex h-full min-w-0 flex-1 items-end justify-center gap-px"><div title={`${item.conversations} conversations`} className="w-1/2 min-w-1 rounded-t bg-gold/70 transition hover:bg-gold" style={{ height: `${Math.max(item.conversations ? 4 : 0, item.conversations / max * 100)}%` }} /><div title={`${item.bookings} bookings`} className="w-1/2 min-w-1 rounded-t bg-ok/70 transition hover:bg-ok" style={{ height: `${Math.max(item.bookings ? 4 : 0, item.bookings / max * 100)}%` }} /><span className="pointer-events-none absolute -top-8 hidden whitespace-nowrap rounded bg-panel-2 px-2 py-1 text-[10px] shadow group-hover:block">{item.date}: {item.conversations} / {item.bookings}</span></div>)}</div>; }
function FunnelRow({ label, value, base }: { label: string; value: number; base: number }) { const percentage = base ? Math.min(100, value / base * 100) : 0; return <div><div className="flex justify-between text-sm"><span>{label}</span><span data-no-translate>{value} · {percentage.toFixed(1)}%</span></div><div className="mt-2 h-2 overflow-hidden rounded-full bg-panel-2"><div className="h-full rounded-full bg-gradient-to-r from-gold to-gold-2" style={{ width: `${percentage}%` }} /></div></div>; }
function SmallMetric({ label, value }: { label: string; value: string | number }) { return <div className="rounded-2xl bg-panel-2/60 p-4"><p className="text-[10px] uppercase tracking-wider text-muted">{label}</p><p className="mt-2 font-serif text-2xl text-gold-2" data-no-translate>{value}</p></div>; }
function RankedList({ rows, empty }: { rows: Array<{ label: string; value: string }>; empty: string }) { return rows.length ? <ol className="mt-5 space-y-3">{rows.map((row, index) => <li key={row.label} className="flex items-center gap-3"><span className="grid h-7 w-7 shrink-0 place-items-center rounded-full bg-gold/10 text-xs text-gold-2" data-no-translate>{index + 1}</span><span className="min-w-0 flex-1 truncate text-sm">{row.label}</span><span className="shrink-0 text-xs text-muted" data-no-translate>{row.value}</span></li>)}</ol> : <p className="mt-6 text-sm text-muted">{empty}</p>; }
function LiveBadge({ connected, generatedAt }: { connected: boolean; generatedAt: string }) { const { locale } = usePreferences(); return <span className="mr-2 flex items-center gap-2 rounded-full border border-line bg-panel px-3 py-2 text-xs" data-no-translate><i className={`h-2 w-2 rounded-full ${connected ? "bg-ok" : "bg-danger"}`} />{connected ? "Live" : "Reconnecting"} · {new Intl.DateTimeFormat(locale, { hour: "2-digit", minute: "2-digit" }).format(new Date(generatedAt))}</span>; }
function formatMetric(value: number | null, format: string, currency: string) { if (value == null) return "—"; if (format === "currency") return formatCurrency(value, currency); if (format === "percent") return `${value.toFixed(1)}%`; if (format === "seconds") return `${value.toFixed(1)}s`; return new Intl.NumberFormat().format(value); }
function formatCurrency(value: number, currency: string) { return new Intl.NumberFormat("en-AE", { style: "currency", currency, maximumFractionDigits: 0 }).format(value); }
function humanize(value: string) { return value.toLowerCase().replaceAll("_", " ").replace(/^./, (letter) => letter.toUpperCase()); }
