"use client";

import Link from "next/link";
import { useRouter } from "next/navigation";
import { useState, type FormEvent } from "react";

type DocumentRow = { id: string; title: string; category: string; keywords: string[]; content: string; fileName: string; fileUrl: string | null; mimeType: string; status: "DRAFT" | "VERIFIED" | "FAILED" | "ARCHIVED"; errorMessage: string | null; verifiedAt: string | null; verifiedBy: string | null; expiresAt: string | null; updatedAt: string };
type EntryRow = { id: string; title: string; body: string; category: string; keywords: string[]; active: boolean; updatedAt: string };

export function KnowledgeBaseManager({ documents, entries, stats }: { documents: DocumentRow[]; entries: EntryRow[]; stats: { queryCount: number; missedQueries: number } }) {
  const router = useRouter();
  const [tab, setTab] = useState<"documents" | "answers">("documents");
  const [busy, setBusy] = useState(false); const [message, setMessage] = useState(""); const [error, setError] = useState("");
  const verified = documents.filter((item) => item.status === "VERIFIED").length + entries.filter((item) => item.active).length;
  const coverage = stats.queryCount ? Math.round(((stats.queryCount - stats.missedQueries) / stats.queryCount) * 100) : 100;

  async function upload(event: FormEvent<HTMLFormElement>) {
    event.preventDefault(); const form = event.currentTarget; setBusy(true); setError(""); setMessage("");
    const response = await fetch("/api/admin/knowledge/documents", { method: "POST", body: new FormData(form) });
    const body = await response.json(); setBusy(false);
    if (!response.ok) return setError(body.error ?? "Could not upload document");
    form.reset(); setMessage(body.document.status === "FAILED" ? "File saved, but text extraction needs attention." : "Document uploaded as draft. Review it before verification."); router.refresh();
  }

  async function createAnswer(event: FormEvent<HTMLFormElement>) {
    event.preventDefault(); const formElement = event.currentTarget; setBusy(true); setError(""); setMessage(""); const form = new FormData(formElement);
    const response = await fetch("/api/admin/cms/knowledge", { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify({ title: form.get("title"), category: form.get("category"), keywords: String(form.get("keywords") || "").split(",").map((item) => item.trim()).filter(Boolean), body: form.get("body"), active: true }) });
    const body = await response.json(); setBusy(false); if (!response.ok) return setError(body.error ?? "Could not add verified answer"); formElement.reset(); setMessage("Verified answer added to the AI knowledge base."); router.refresh();
  }

  return <div>
    <div className="flex flex-col gap-4 sm:flex-row sm:items-end sm:justify-between"><div><p className="text-xs uppercase tracking-[0.22em] text-gold">AI truth layer</p><h2 className="mt-2 font-serif text-5xl">Knowledge base</h2><p className="mt-3 max-w-3xl text-sm leading-6 text-muted">Upload business documents or add verified answers. Drafts are never shown to the AI; only reviewed, current sources can be retrieved during a client conversation.</p></div><Link href="/admin/analytics" className="btn-ghost text-sm">View knowledge analytics</Link></div>
    <div className="mt-8 grid gap-4 sm:grid-cols-3"><Metric label="Verified sources" value={verified} detail="Available to the AI now" /><Metric label="30-day searches" value={stats.queryCount} detail="Knowledge retrieval attempts" /><Metric label="Answer coverage" value={`${coverage}%`} detail={`${stats.missedQueries} questions lacked a match`} /></div>
    <section className="admin-card mt-6 rounded-3xl p-5 sm:p-7"><div className="flex flex-wrap gap-2 border-b border-line pb-5"><button type="button" onClick={() => setTab("documents")} className={tab === "documents" ? "btn-gold" : "btn-ghost"}>Training documents</button><button type="button" onClick={() => setTab("answers")} className={tab === "answers" ? "btn-gold" : "btn-ghost"}>Verified answers</button></div>
      {error ? <p className="mt-5 rounded-xl bg-danger/10 p-3 text-sm text-danger" role="alert">{error}</p> : null}{message ? <p className="mt-5 rounded-xl bg-ok/10 p-3 text-sm text-ok" role="status">{message}</p> : null}
      {tab === "documents" ? <div><form onSubmit={upload} className="mt-6 grid gap-4 rounded-2xl bg-panel-2/55 p-5 md:grid-cols-2"><div><label htmlFor="doc-title">Document title</label><input id="doc-title" name="title" required maxLength={200} placeholder="Delivery and collection guide" /></div><div><label htmlFor="doc-category">Category</label><input id="doc-category" name="category" required defaultValue="Operations" maxLength={80} /></div><div><label htmlFor="doc-keywords">Keywords</label><input id="doc-keywords" name="keywords" placeholder="delivery, airport, collection" /></div><div><label htmlFor="doc-expiry">Review / expiry date</label><input id="doc-expiry" name="expiresAt" type="date" /></div><div className="md:col-span-2"><label htmlFor="doc-file">PDF, TXT, Markdown, CSV, or JSON</label><input id="doc-file" name="file" type="file" required accept=".pdf,.txt,.md,.csv,.json,application/pdf,text/plain,text/markdown,text/csv,application/json" /></div><button disabled={busy} className="btn-gold md:col-span-2 md:w-fit">{busy ? "Processing…" : "Upload as draft"}</button></form><div className="mt-6 space-y-4">{documents.length ? documents.map((document) => <DocumentCard key={document.id} document={document} onError={setError} onMessage={setMessage} />) : <Empty text="No training documents yet. Upload the first source above." />}</div></div> : null}
      {tab === "answers" ? <div><form onSubmit={createAnswer} className="mt-6 grid gap-4 rounded-2xl bg-panel-2/55 p-5 md:grid-cols-2"><div><label htmlFor="answer-title">Topic or question</label><input id="answer-title" name="title" required maxLength={200} /></div><div><label htmlFor="answer-category">Category</label><input id="answer-category" name="category" required defaultValue="General" /></div><div className="md:col-span-2"><label htmlFor="answer-keywords">Keywords</label><input id="answer-keywords" name="keywords" placeholder="comma, separated, search terms" /></div><div className="md:col-span-2"><label htmlFor="answer-body">Verified business answer</label><textarea id="answer-body" name="body" required rows={7} maxLength={12000} /></div><button disabled={busy} className="btn-gold md:col-span-2 md:w-fit">Add verified answer</button></form><div className="mt-6 space-y-3">{entries.length ? entries.map((entry) => <div key={entry.id} className="rounded-2xl border border-line p-5"><div className="flex items-start justify-between gap-4"><div><p className="font-medium">{entry.title}</p><p className="mt-1 text-xs text-muted">{entry.category} · Updated {new Date(entry.updatedAt).toLocaleDateString()}</p></div><span className={`rounded-full px-2 py-1 text-[10px] uppercase tracking-wider ${entry.active ? "bg-ok/10 text-ok" : "bg-panel-2 text-muted"}`}>{entry.active ? "Verified" : "Inactive"}</span></div><p className="mt-4 line-clamp-3 whitespace-pre-line text-sm leading-6 text-muted">{entry.body}</p></div>) : <Empty text="No verified answers yet." />}</div><Link href="/admin/content" className="mt-5 inline-block text-sm text-gold">Edit existing answers in Content studio →</Link></div> : null}
    </section>
  </div>;
}

function DocumentCard({ document, onError, onMessage }: { document: DocumentRow; onError: (value: string) => void; onMessage: (value: string) => void }) {
  const router = useRouter(); const [value, setValue] = useState(document); const [busy, setBusy] = useState(false);
  async function mutate(status?: "DRAFT" | "VERIFIED" | "ARCHIVED", method: "PATCH" | "DELETE" = "PATCH") { setBusy(true); onError(""); onMessage(""); const nextStatus = status ?? (value.status === "FAILED" ? "DRAFT" : value.status); const response = await fetch(`/api/admin/knowledge/documents/${document.id}`, { method, headers: { "content-type": "application/json" }, ...(method === "PATCH" ? { body: JSON.stringify({ title: value.title, category: value.category, keywords: value.keywords, content: value.content, expiresAt: value.expiresAt, status: nextStatus }) } : {}) }); const body = await response.json(); setBusy(false); if (!response.ok) return onError(body.error ?? "Document update failed"); onMessage(method === "DELETE" ? "Document deleted." : status === "VERIFIED" ? "Document verified and available to the AI." : "Document saved."); router.refresh(); }
  return <article className="rounded-2xl border border-line p-5"><div className="flex flex-col gap-4 sm:flex-row sm:items-start sm:justify-between"><div className="min-w-0"><input aria-label="Document title" value={value.title} onChange={(event) => setValue({ ...value, title: event.target.value })} className="border-0 bg-transparent p-0 text-lg font-medium" /><p className="mt-2 text-xs text-muted" data-no-translate>{document.fileName} · {document.mimeType} · Updated {new Date(document.updatedAt).toLocaleDateString()}</p></div><Status value={document.status} /></div>{document.errorMessage ? <p className="mt-4 rounded-xl bg-danger/10 p-3 text-sm text-danger">{document.errorMessage}</p> : null}<div className="mt-4 grid gap-4 sm:grid-cols-2"><div><label>Category</label><input value={value.category} onChange={(event) => setValue({ ...value, category: event.target.value })} /></div><div><label>Keywords</label><input value={value.keywords.join(", ")} onChange={(event) => setValue({ ...value, keywords: event.target.value.split(",").map((item) => item.trim()).filter(Boolean) })} /></div></div><div className="mt-4"><label>Extracted and reviewed content</label><textarea rows={8} value={value.content} onChange={(event) => setValue({ ...value, content: event.target.value })} /></div><div className="mt-4 flex flex-wrap items-center justify-between gap-3"><div className="flex gap-3">{document.fileUrl ? <a href={document.fileUrl} target="_blank" rel="noreferrer" className="text-sm text-gold">Original file</a> : null}{document.verifiedBy ? <span className="text-xs text-muted" data-no-translate>Verified by {document.verifiedBy}</span> : null}</div><div className="flex flex-wrap gap-2"><button disabled={busy} type="button" onClick={() => void mutate(undefined)} className="btn-ghost">Save draft</button>{document.status !== "VERIFIED" ? <button disabled={busy || !value.content.trim()} type="button" onClick={() => void mutate("VERIFIED")} className="btn-gold">Verify for AI</button> : <button disabled={busy} type="button" onClick={() => void mutate("DRAFT")} className="btn-ghost">Return to draft</button>}<button disabled={busy} type="button" onClick={() => void mutate("ARCHIVED")} className="btn-ghost">Archive</button><button disabled={busy} type="button" onClick={() => void mutate(undefined, "DELETE")} className="btn-ghost text-danger">Delete</button></div></div></article>;
}
function Metric({ label, value, detail }: { label: string; value: string | number; detail: string }) { return <div className="admin-card rounded-2xl p-5"><p className="text-xs uppercase tracking-widest text-muted">{label}</p><p className="mt-3 font-serif text-4xl text-gold-2" data-no-translate>{value}</p><p className="mt-1 text-xs text-muted">{detail}</p></div>; }
function Status({ value }: { value: DocumentRow["status"] }) { const tone = value === "VERIFIED" ? "bg-ok/10 text-ok" : value === "FAILED" ? "bg-danger/10 text-danger" : "bg-gold/10 text-gold-2"; return <span className={`w-fit rounded-full px-3 py-1 text-[10px] font-semibold uppercase tracking-wider ${tone}`}>{value}</span>; }
function Empty({ text }: { text: string }) { return <div className="rounded-2xl border border-dashed border-line p-8 text-center text-sm text-muted">{text}</div>; }
