ALTER TABLE "Quote" ADD COLUMN "currency" TEXT;

ALTER TABLE "CmsSettings"
  ALTER COLUMN "businessName" SET DEFAULT '',
  ALTER COLUMN "tagline" SET DEFAULT '',
  ALTER COLUMN "businessDescription" SET DEFAULT '',
  ALTER COLUMN "city" SET DEFAULT '',
  ALTER COLUMN "country" SET DEFAULT '',
  ALTER COLUMN "timezone" SET DEFAULT '',
  ALTER COLUMN "currency" SET DEFAULT '',
  ALTER COLUMN "seoTitle" SET DEFAULT '',
  ALTER COLUMN "seoDescription" SET DEFAULT '',
  ALTER COLUMN "heroEyebrow" SET DEFAULT '',
  ALTER COLUMN "heroTitle" SET DEFAULT '',
  ALTER COLUMN "heroSubtitle" SET DEFAULT '',
  ALTER COLUMN "heroPrimaryLabel" SET DEFAULT '',
  ALTER COLUMN "heroSecondaryLabel" SET DEFAULT '',
  ALTER COLUMN "aboutTitle" SET DEFAULT '',
  ALTER COLUMN "aboutBody" SET DEFAULT '',
  ALTER COLUMN "fleetTitle" SET DEFAULT '',
  ALTER COLUMN "fleetBody" SET DEFAULT '',
  ALTER COLUMN "faqTitle" SET DEFAULT '',
  ALTER COLUMN "contactTitle" SET DEFAULT '',
  ALTER COLUMN "contactBody" SET DEFAULT '',
  ALTER COLUMN "footerText" SET DEFAULT '',
  ALTER COLUMN "agentTone" SET DEFAULT '',
  ALTER COLUMN "salesScript" SET DEFAULT '',
  ALTER COLUMN "agentGreeting" SET DEFAULT '',
  ALTER COLUMN "agentHandoffMessage" SET DEFAULT '',
  ALTER COLUMN "prohibitedClaims" SET DEFAULT '';
